<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>前端异常处理 | YolkPie</title><meta name="description" content="前言为什么要处理前端异常，有以下几方面的原因：  提高代码健壮性：对于开发人员来说，这点很重要，代码的健壮性越好，系统越不容易崩溃； 提升系统稳定性：异常会导致正常流程无法进行、页面样式错乱、崩溃甚至白屏等问题，严重的会给业务造成损失； 增强用户体验：代码的错误不应该影响页面的正常显示和用户交互，出错时我们需要使用拖底方案或者给用户反馈； 便于定位问题：只有知道了如何处理异常，我们才能将异常正常上"><meta name="keywords" content="异常"><meta name="author" content="YolkPie"><meta name="copyright" content="YolkPie"><meta name="format-detection" content="telephone=no"><link rel="shortcut icon" href="/img/favicon.png"><link rel="canonical" href="https://yolkpie.net/2021/01/28/%E5%89%8D%E7%AB%AF%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/"><meta http-equiv="Cache-Control" content="no-transform"><meta http-equiv="Cache-Control" content="no-siteapp"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="preconnect" href="//fonts.googleapis.com" crossorigin="crossorigin"/><link rel="preconnect" href="//busuanzi.ibruce.info"/><meta property="og:type" content="article"><meta property="og:title" content="前端异常处理"><meta property="og:url" content="https://yolkpie.net/2021/01/28/%E5%89%8D%E7%AB%AF%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/"><meta property="og:site_name" content="YolkPie"><meta property="og:description" content="前言为什么要处理前端异常，有以下几方面的原因：  提高代码健壮性：对于开发人员来说，这点很重要，代码的健壮性越好，系统越不容易崩溃； 提升系统稳定性：异常会导致正常流程无法进行、页面样式错乱、崩溃甚至白屏等问题，严重的会给业务造成损失； 增强用户体验：代码的错误不应该影响页面的正常显示和用户交互，出错时我们需要使用拖底方案或者给用户反馈； 便于定位问题：只有知道了如何处理异常，我们才能将异常正常上"><meta property="og:image" content="https://img12.360buyimg.com/imagetools/jfs/t1/169203/7/4620/173190/601266a8E8ad356b4/4fdec47d3f9e5259.png"><meta property="article:published_time" content="2021-01-28T07:15:00.000Z"><meta property="article:modified_time" content="2022-05-11T10:55:14.673Z"><meta name="twitter:card" content="summary"><script>var activateDarkMode = function () {
  document.documentElement.setAttribute('data-theme', 'dark')
  if (document.querySelector('meta[name="theme-color"]') !== null) {
    document.querySelector('meta[name="theme-color"]').setAttribute('content', '#000')
  }
}
var activateLightMode = function () {
  document.documentElement.setAttribute('data-theme', 'light')
  if (document.querySelector('meta[name="theme-color"]') !== null) {
    document.querySelector('meta[name="theme-color"]').setAttribute('content', '#fff')
  }
}

var getCookies = function (name) {
  const value = `; ${document.cookie}`
  const parts = value.split(`; ${name}=`)
  if (parts.length === 2) return parts.pop().split(';').shift()
}

var autoChangeMode = 'false'
var t = getCookies('theme')
if (autoChangeMode === '1') {
  var isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches
  var isLightMode = window.matchMedia('(prefers-color-scheme: light)').matches
  var isNotSpecified = window.matchMedia('(prefers-color-scheme: no-preference)').matches
  var hasNoSupport = !isDarkMode && !isLightMode && !isNotSpecified

  if (t === undefined) {
    if (isLightMode) activateLightMode()
    else if (isDarkMode) activateDarkMode()
    else if (isNotSpecified || hasNoSupport) {
      console.log('You specified no preference for a color scheme or your browser does not support it. I Schedule dark mode during night time.')
      var now = new Date()
      var hour = now.getHours()
      var isNight = hour <= 6 || hour >= 18
      isNight ? activateDarkMode() : activateLightMode()
    }
    window.matchMedia('(prefers-color-scheme: dark)').addListener(function (e) {
      if (Cookies.get('theme') === undefined) {
        e.matches ? activateDarkMode() : activateLightMode()
      }
    })
  } else if (t === 'light') activateLightMode()
  else activateDarkMode()
} else if (autoChangeMode === '2') {
  now = new Date()
  hour = now.getHours()
  isNight = hour <= 6 || hour >= 18
  if (t === undefined) isNight ? activateDarkMode() : activateLightMode()
  else if (t === 'light') activateLightMode()
  else activateDarkMode()
} else {
  if (t === 'dark') activateDarkMode()
  else if (t === 'light') activateLightMode()
}</script><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css"><link rel="prev" title="SameSiteForCookie" href="https://yolkpie.net/2021/02/03/SameSiteForCookie/"><link rel="next" title="React Hooks的常见应用及一些原理" href="https://yolkpie.net/2021/01/28/React%20Hooks%E7%9A%84%E5%B8%B8%E8%A7%81%E5%BA%94%E7%94%A8%E5%8F%8A%E4%B8%80%E4%BA%9B%E5%8E%9F%E7%90%86/"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Titillium+Web&amp;display=swap"><script>var GLOBAL_CONFIG = { 
  root: '/',
  algolia: undefined,
  localSearch: undefined,
  translate: {"defaultEncoding":2,"translateDelay":0,"msgToTraditionalChinese":"繁","msgToSimplifiedChinese":"簡"},
  copy: {
    success: '复制成功',
    error: '复制错误',
    noSupport: '浏览器不支持'
  },
  bookmark: {
    message_prev: '按',
    message_next: '键将本页加入书签'
  },
  runtime_unit: '天',
  runtime: false,
  copyright: undefined,
  ClickShowText: undefined,
  medium_zoom: false,
  fancybox: true,
  Snackbar: undefined,
  justifiedGallery: {
    js: 'https://cdn.jsdelivr.net/npm/justifiedGallery/dist/js/jquery.justifiedGallery.min.js',
    css: 'https://cdn.jsdelivr.net/npm/justifiedGallery/dist/css/justifiedGallery.min.css'
  },
  baiduPush: false,
  highlightCopy: true,
  highlightLang: true,
  isPhotoFigcaption: false,
  islazyload: true,
  isanchor: false    
}</script><script>var GLOBAL_CONFIG_SITE = { 
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isSidebar: true
  }</script><noscript><style>
#nav {
  opacity: 1
}
.justified-gallery img{
  opacity: 1
}
</style></noscript><meta name="generator" content="Hexo 5.0.0"></head><body><div id="mobile-sidebar"><div id="menu_mask"></div><div id="mobile-sidebar-menus"><div class="mobile_author_icon"><img class="avatar-img" src="/img/avatar.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="mobile_post_data"><div class="mobile_data_item is-center"><div class="mobile_data_link"><a href="/archives/"><div class="headline">文章</div><div class="length_num">160</div></a></div></div><div class="mobile_data_item is-center">      <div class="mobile_data_link"><a href="/tags/"><div class="headline">标签</div><div class="length_num">83</div></a></div></div><div class="mobile_data_item is-center">     <div class="mobile_data_link"><a href="/categories/"><div class="headline">分类</div><div class="length_num">35</div></a></div></div></div><hr/><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Archives</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> Link</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><i class="fas fa-arrow-right on" id="toggle-sidebar"></i><div id="sidebar"><div class="sidebar-toc"><div class="sidebar-toc__title">目录</div><div class="sidebar-toc__progress"><span class="progress-notice">你已经读了</span><span class="progress-num">0</span><span class="progress-percentage">%</span><div class="sidebar-toc__progress-bar">     </div></div><div class="sidebar-toc__content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E5%89%8D%E8%A8%80"><span class="toc-number">1.</span> <span class="toc-text">前言</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#Error-%E5%8F%8A-Error-%E7%B1%BB%E5%9E%8B"><span class="toc-number">2.</span> <span class="toc-text">Error 及 Error 类型</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#Error-%E5%AF%B9%E8%B1%A1"><span class="toc-number">2.1.</span> <span class="toc-text">Error 对象</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Error%E7%B1%BB%E5%9E%8B"><span class="toc-number">2.2.</span> <span class="toc-text">Error类型</span></a></li></ol></li><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%8D%95%E8%8E%B7%E5%BC%82%E5%B8%B8"><span class="toc-number">3.</span> <span class="toc-text">捕获异常</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E9%80%9A%E7%94%A8%E6%96%B9%E5%BC%8F"><span class="toc-number">3.1.</span> <span class="toc-text">通用方式</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#try-catch"><span class="toc-number">3.1.1.</span> <span class="toc-text">try-catch</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#GlobalEventHandlers-onerror"><span class="toc-number">3.1.2.</span> <span class="toc-text">GlobalEventHandlers.onerror</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#promise-catch"><span class="toc-number">3.1.3.</span> <span class="toc-text">promise-catch</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#unhandledrejection"><span class="toc-number">3.1.4.</span> <span class="toc-text">unhandledrejection</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Vue-%E4%B8%AD%E6%8D%95%E8%8E%B7%E5%BC%82%E5%B8%B8"><span class="toc-number">3.2.</span> <span class="toc-text">Vue 中捕获异常</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#errorHandler"><span class="toc-number">3.2.1.</span> <span class="toc-text">errorHandler</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#errorCaptured"><span class="toc-number">3.2.2.</span> <span class="toc-text">errorCaptured</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#React-%E4%B8%AD%E6%8D%95%E8%8E%B7%E5%BC%82%E5%B8%B8"><span class="toc-number">3.3.</span> <span class="toc-text">React 中捕获异常</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E9%94%99%E8%AF%AF%E8%BE%B9%E7%95%8C"><span class="toc-number">3.3.1.</span> <span class="toc-text">错误边界</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#iframe-%E5%BC%82%E5%B8%B8"><span class="toc-number">3.4.</span> <span class="toc-text">iframe 异常</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E9%A1%B5%E9%9D%A2%E5%B4%A9%E6%BA%83"><span class="toc-number">3.5.</span> <span class="toc-text">页面崩溃</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#load-%E5%92%8C-beforeunload-%E4%BA%8B%E4%BB%B6"><span class="toc-number">3.5.1.</span> <span class="toc-text">load 和 beforeunload 事件</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%9F%BA%E4%BA%8E-Service-Worker"><span class="toc-number">3.5.2.</span> <span class="toc-text">基于 Service Worker</span></a></li></ol></li></ol></li><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%80%BB%E7%BB%93"><span class="toc-number">4.</span> <span class="toc-text">总结</span></a></li></ol></div></div></div><div id="body-wrap"><header class="post-bg" id="page-header" style="background-image: url(https://img12.360buyimg.com/imagetools/jfs/t1/169203/7/4620/173190/601266a8E8ad356b4/4fdec47d3f9e5259.png)"><nav id="nav"><span class="pull-left" id="blog_name"><a class="blog_title" id="site-name" href="/">YolkPie</a></span><span class="pull-right menus"><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Archives</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> Link</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><span class="toggle-menu close"><a class="site-page"><i class="fas fa-bars fa-fw"></i></a></span></span></nav><div id="post-info"><div id="post-title"><div class="posttitle">前端异常处理</div></div><div id="post-meta"><div class="meta-firstline"><time class="post-meta__date"><span class="post-meta__date-created" title="发表于 2021-01-28 15:15:00"><i class="far fa-calendar-alt fa-fw"></i> 发表于 2021-01-28</span><span class="post-meta__separator">|</span><span class="post-meta__date-updated" title="更新于 2022-05-11 18:55:14"><i class="fas fa-history fa-fw"></i> 更新于 2022-05-11</span></time></div><div class="meta-secondline"> </div><div class="meta-thirdline"><span class="post-meta-pv-cv"><i class="far fa-eye fa-fw post-meta__icon"></i><span>阅读量:</span><span id="busuanzi_value_page_pv"></span></span><span class="post-meta-commentcount"></span></div></div></div></header><main class="layout_post" id="content-inner"><article id="post"><div class="post-content" id="article-container"><h1 id="前言"><a href="#前言" class="headerlink" title="前言"></a>前言</h1><p>为什么要处理前端异常，有以下几方面的原因：</p>
<ol>
<li>提高代码健壮性：对于开发人员来说，这点很重要，代码的健壮性越好，系统越不容易崩溃；</li>
<li>提升系统稳定性：异常会导致正常流程无法进行、页面样式错乱、崩溃甚至白屏等问题，严重的会给业务造成损失；</li>
<li>增强用户体验：代码的错误不应该影响页面的正常显示和用户交互，出错时我们需要使用拖底方案或者给用户反馈；</li>
<li>便于定位问题：只有知道了如何处理异常，我们才能将异常正常上报给前端监控系统，及时发现并定位问题。</li>
</ol>
<p>本文分为以下三个部分：<br>第一部分：介绍 Error 对象及 Error 的类型；<br>第二部分：介绍捕获异常的方式有哪些，包含通用、Vue和React项目、iframe中的捕获以及页面崩溃异常的获取；<br>第三部分：结合工作中的场景，总结各自对应的异常处理方式。</p>
<p>这篇文章的前两部分我尽量都提供了对应的示例，希望这些示例对你们有用。另外，由于这篇文章是做汇总用的，会比较长，各位可以按自己的需要去看对应的部分。</p>
<h1 id="Error-及-Error-类型"><a href="#Error-及-Error-类型" class="headerlink" title="Error 及 Error 类型"></a>Error 及 Error 类型</h1><p>说到异常，我们需要先从 Error 对象讲起。当 JavaScript 运行时，如果发生了错误，浏览器就会抛出 Error 的实例对象。</p>
<h2 id="Error-对象"><a href="#Error-对象" class="headerlink" title="Error 对象"></a>Error 对象</h2><p>Error 是 JavaScript 中的错误类，它同时也是一个构造函数，可以用来创建一个错误对象。创建Error 实例对象的方法如下：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">new</span> <span class="built_in">Error</span>([message[, fileName[,lineNumber]]]);</span><br></pre></td></tr></table></figure>

<p>此外，Error 可以像函数一样使用，如果没有 new，它将返回一个 Error 实例对象。所以， 仅仅调用 Error 产生的结果与通过 new 关键字构造 Error 实例对象生成的结果相同。</p>
<h2 id="Error类型"><a href="#Error类型" class="headerlink" title="Error类型"></a>Error类型</h2><p>参照<a target="_blank" rel="noopener" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error">MDN的文档</a>, 还有以下错误类型都继承自 Error 对象：</p>
<ul>
<li>SyntaxError</li>
<li>RangeError</li>
<li>ReferenceError</li>
<li>TypeError</li>
<li>URIError</li>
<li>EvalError</li>
<li>InternalError</li>
<li>AggregateError</li>
</ul>
<p>接下来我将按顺序介绍上述错误类型的含义，并尽量举出对应的例子。</p>
<ol>
<li>SyntaxError</li>
</ol>
<p>SyntaxError 是代码不符合 Javascript 语法规范产生的错误。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 变量名错误</span></span><br><span class="line"><span class="keyword">let</span> 1name <span class="comment">// Uncaught SyntaxError: Invalid or unexpected token</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 缺少括号</span></span><br><span class="line"><span class="built_in">console</span>.log(<span class="string">&#x27;test&#x27;</span> <span class="comment">// Uncaught SyntaxError: missing ) after argument list</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 字符串没有加引号</span></span><br><span class="line">a string <span class="comment">// Uncaught SyntaxError: Unexpected identifier</span></span><br></pre></td></tr></table></figure>

<ol start="2">
<li>RangeError</li>
</ol>
<p>RangeError 是当一个值不在允许的范围或者集合中时的错误。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 传递一个不合法的length值作为Array构造器的参数创建数组</span></span><br><span class="line"><span class="keyword">new</span> <span class="built_in">Array</span>(-<span class="number">1</span>) <span class="comment">// Uncaught RangeError: Invalid array length</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 传递错误值到数值计算方法</span></span><br><span class="line"><span class="keyword">var</span> number = <span class="number">10</span></span><br><span class="line">number.toFixed(-<span class="number">1</span>) <span class="comment">// Uncaught RangeError: toFixed() digits argument must be between 0 and 100</span></span><br></pre></td></tr></table></figure>

<ol start="3">
<li>ReferenceError</li>
</ol>
<p>ReferenceError 是引用一个不存在的变量或者给不能赋值的对象赋值时发生的错误。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 变量名未定义</span></span><br><span class="line">undefinedVariable <span class="comment">// Uncaught ReferenceError: unknowName is not defined</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 方法名未定义</span></span><br><span class="line">undefinedFunction() <span class="comment">// Uncaught ReferenceError: undefinedFunction is not defined</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 等号左侧不能赋值 //todo: 为啥</span></span><br><span class="line"><span class="built_in">console</span>.log() = <span class="number">1</span> <span class="comment">// Uncaught SyntaxError: Invalid left-hand side in assignment</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 等号左侧不能赋值 //todo: 为啥</span></span><br><span class="line"><span class="keyword">if</span>(a === <span class="number">1</span> || b = <span class="number">2</span>) &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;a === 1 || b = 2&#x27;</span>)</span><br><span class="line">&#125; <span class="comment">// Invalid left-hand side in assignment</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// this对象不能手动赋值</span></span><br><span class="line"><span class="built_in">this</span> = <span class="number">1</span> <span class="comment">// Uncaught SyntaxError: Invalid left-hand side in assignment</span></span><br></pre></td></tr></table></figure>

<ol start="4">
<li>TypeError</li>
</ol>
<p>TypeError 是变量或参数的类型不是预期类型时发生的错误。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// new命令的参数不是构造函数</span></span><br><span class="line"><span class="keyword">new</span> <span class="number">123</span> <span class="comment">// Uncaught TypeError: 123 is not a constructor</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 使用的方法不是function</span></span><br><span class="line"><span class="keyword">let</span> functionName = <span class="string">&#x27;functionName&#x27;</span></span><br><span class="line">functionName() <span class="comment">// Uncaught TypeError: functionName is not a function</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// undefined或null没有对应的属性或方法</span></span><br><span class="line"><span class="literal">undefined</span>.value <span class="comment">// Uncaught TypeError: Cannot read property &#x27;value&#x27; of undefined</span></span><br></pre></td></tr></table></figure>

<ol start="5">
<li>URIError</li>
</ol>
<p>URIError 是 URI 相关函数的参数不正确时抛出的错误。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">decodeURI</span>(<span class="string">&#x27;%&#x27;</span>) <span class="comment">// Uncaught URIError: URI malformed</span></span><br></pre></td></tr></table></figure>

<ol start="6">
<li>EvalError</li>
</ol>
<p>EvalError 表示 eval 函数没有被正确执行时发生的错误。需要注意的是此异常不再会被JavaScript 抛出，但是 EvalError 对象仍然保持兼容性。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 没有报EvalError而是对应执行js时的SyntaxError</span></span><br><span class="line"><span class="built_in">eval</span>(<span class="string">&#x27;a string&#x27;</span>) <span class="comment">// Uncaught SyntaxError: Unexpected identifier</span></span><br></pre></td></tr></table></figure>

<blockquote>
<p>永远不要使用 eval！<br>eval() 是一个危险的函数， 它使用与调用者相同的权限执行代码。如果你用 eval() 运行的字符串代码被恶意方（不怀好意的人）修改，您最终可能会在您的网页/扩展程序的权限下，在用户计算机上运行恶意代码。<br>eval() 通常比其他替代方法更慢，因为它必须调用 JS 解释器，而许多其他结构则可被现代 JS 引擎进行优化。</p>
</blockquote>
<ol start="7">
<li>InternalError</li>
</ol>
<p>InternalError 表示出现在 JavaScript 引擎内部的错误。</p>
<blockquote>
<p>示例场景通常为某些成分过大，例如：</p>
<ul>
<li>“too many switch cases”（过多case子句）；</li>
<li>“too many parentheses in regular expression”（正则表达式中括号过多）；</li>
<li>“array initializer too large”（数组初始化器过大）；</li>
<li>“too much recursion”（递归过深）。</li>
</ul>
</blockquote>
<ol start="8">
<li>AggregateError</li>
</ol>
<p>AggregateError 是用于把多个错误集合在一起。需要注意的是这是一个实验中的功能，尚未被所有的浏览器支持（下面例子中用到的 Promise.any 也是实验中的功能）。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">Promise</span>.any([</span><br><span class="line">  <span class="built_in">Promise</span>.reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">&quot;some error&quot;</span>))</span><br><span class="line">]) <span class="comment">// Uncaught (in promise) AggregateError: All promises were rejected</span></span><br></pre></td></tr></table></figure>

<blockquote>
<p>Promise.any() 接收一个 Promise 可迭代对象，只要其中的一个 promise 成功，就返回那个已经成功的 promise。如果可迭代对象中没有一个 promise 成功（即所有的 promises 都失败/拒绝），就返回一个失败的 promise 和 AggregateError 类型的实例。</p>
</blockquote>
<p>我们还可以基于 Error 自定义异常类型，或者用 throw 方法抛出任意类型的异常，但我们本文的目标在于捕获并处理浏览器抛出的异常，这里对自定义的异常和手动 throw 的异常不做过多说明。</p>
<h1 id="捕获异常"><a href="#捕获异常" class="headerlink" title="捕获异常"></a>捕获异常</h1><p>在了解了浏览器会抛出哪些异常后，我们现在来进一步了解在代码层面我们可以做些什么来捕获这些异常，从而协助我们提升代码的健壮性。</p>
<h2 id="通用方式"><a href="#通用方式" class="headerlink" title="通用方式"></a>通用方式</h2><h3 id="try-catch"><a href="#try-catch" class="headerlink" title="try-catch"></a>try-catch</h3><p>try-catch 语句标记要尝试的语句块，并指定一个出现异常时抛出的响应。try 语句包含了由一个或者多个语句组成的 try 块，catch 子句包含 try 块中抛出异常时要执行的语句。如果在 try 块中有任何一个语句（或者从 try 块中调用的函数）抛出异常，控制立即转向 catch 子句。如果在 try 块中没有异常抛出，会跳过 catch 子句。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="keyword">const</span> person = &#123;&#125;;</span><br><span class="line">  <span class="built_in">console</span>.log(person.info.name);</span><br><span class="line">&#125; <span class="keyword">catch</span> (err) &#123;</span><br><span class="line">  <span class="built_in">console</span>.log(err);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// TypeError: Cannot read property &#x27;name&#x27; of undefined at &lt;anonymous&gt;:3:27</span></span><br></pre></td></tr></table></figure>

<p>上面的例子中，我们试图获取一个 undefined 对象的属性值，这个异常被 catch 捕获并输出在控制台。</p>
<blockquote>
<p>任何给定的异常只会被离它最近的封闭 catch 块捕获一次。</p>
</blockquote>
<p>有时候，我们代码中也会出现 try-catch 嵌套的情况，如果内层没有 catch 事件，则会被外层 catch 捕获：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">&#x27;error&#x27;</span>);</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">finally</span> &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;finally&#x27;</span>);</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span> (err) &#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;outer&#x27;</span>, err);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// finally</span></span><br><span class="line"><span class="comment">// VM1360:10 outer Error: error at &lt;anonymous&gt;:3:11</span></span><br></pre></td></tr></table></figure>

<p>如果在内层抛出新异常，这个新异常会被外层 catch 捕获：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">&#x27;error&#x27;</span>);</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">catch</span> (err) &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;inner&#x27;</span>, err);</span><br><span class="line">    <span class="keyword">throw</span> err; <span class="comment">// 抛出新异常，没有被内层捕获过</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span> (err) &#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;outer&#x27;</span>, err);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// inner Error: error at &lt;anonymous&gt;:3:11</span></span><br><span class="line"><span class="comment">// outer Error: error at &lt;anonymous&gt;:3:11</span></span><br></pre></td></tr></table></figure>

<p>try-catch 适用于知道某段代码可能出现问题的情况，只能捕获同步的运行时错误，不能捕获语法错误和异步错误：</p>
<ol>
<li>语法错误：语法错误，try-catch 没有正确执行。</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">let</span> 1a = <span class="string">&#x27;a&#x27;</span>;</span><br><span class="line">    <span class="built_in">console</span>.log(1a);</span><br><span class="line">  &#125; <span class="keyword">catch</span> (err) &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;catch syntax error&#x27;</span>);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="comment">// Uncaught SyntaxError: Invalid or unexpected token</span></span><br><span class="line"><span class="string">``</span><span class="string">` </span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">2. 异步错误：因为异步事件已经放入异步事件队列中，无法捕捉到。</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">`</span><span class="string">``</span> js</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="built_in">setTimeout</span>(<span class="function">() =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(a)</span><br><span class="line">    &#125;, <span class="number">1000</span>);</span><br><span class="line">  &#125; <span class="keyword">catch</span> (err) &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;catch async error&#x27;</span>);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="comment">// Uncaught ReferenceError: a is not defined at &lt;anonymous&gt;:3:17</span></span><br></pre></td></tr></table></figure>

<h3 id="GlobalEventHandlers-onerror"><a href="#GlobalEventHandlers-onerror" class="headerlink" title="GlobalEventHandlers.onerror"></a>GlobalEventHandlers.onerror</h3><p>从 GlobalEventHandlers.onerror 字面本身就可以看出，这个 onerror 用于处理全局的错误。我们先来看下 MDN 上对它的解释：</p>
<p>混合事件 GlobalEventHandlers 的 onerror 属性用于处理 error 的事件。</p>
<ul>
<li>当 JavaScript 运行时错误（包括语法错误）发生时，window 会触发一个 ErrorEvent 接口的 error 事件，并执行 window.onerror()。</li>
<li>当一项资源（图片或 JavaScript文件）加载失败，加载资源的元素会触发一个 Event 接口的 error 事件，并执行该元素上的 onerror() 处理函数。这些 error 事件不会向上冒泡到 window，不过（至少在 Firefox 中）能被单一的 window.addEventListener 捕获。  </li>
</ul>
<p>从上面的文字，我们可以得出以下的结论：</p>
<ol>
<li>代码发生运行时错误（包括语法错误）时，会触发 window 的 error 事件，我们可以通 window.onerror 和 window.addEventListener(‘error’, function(event) { … })来捕获；</li>
<li>静态资源加载失败时，会触发加载资源的元素上的 onerror 事件，由于该事件不会冒泡到 winow，因此 window.onerror 是不会捕获到静态资源加载失败的错误的；</li>
<li>如果要使用全局方法捕获静态资源加载失败的错误，可以使用 window.addEventListener。</li>
</ol>
<p>我们还是来通过具体的例子来验证一下，先定义下 window.onerror 和 window.addEventListener 这两个方法（需要写在所有 JavaScript 脚本的前面，否则有可能捕获不到错误）：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">window</span>.onerror = <span class="function"><span class="keyword">function</span>(<span class="params">message, source, lineno, colno, error</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;window.onerror catch error:&#x27;</span>, message);</span><br><span class="line">&#125;</span><br><span class="line"><span class="built_in">window</span>.addEventListener(<span class="string">&#x27;error&#x27;</span>, <span class="function"><span class="keyword">function</span>(<span class="params">event</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;window.addEventListener catch error:&#x27;</span>, event.message)</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure>

<ol>
<li>语法错误</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">let</span> 1a = <span class="string">&#x27;a&#x27;</span>;</span><br><span class="line"><span class="built_in">console</span>.log(1a);</span><br><span class="line"></span><br><span class="line"><span class="comment">// window.onerror catch error: Uncaught SyntaxError: Invalid or unexpected token</span></span><br><span class="line"><span class="comment">// window.addEventListener catch error: Uncaught SyntaxError: Invalid or unexpected token</span></span><br></pre></td></tr></table></figure>

<ol start="2">
<li>静态资源加载错误</li>
</ol>
<p>要捕获静态资源加载失败的错误，我们可以在静态资源上添加 onerror 事件：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">&lt;script src=<span class="string">&quot;https://misc.360buyimg.com/jdf/lib/jquery-1.6.4.000.js&quot;</span> onerror=<span class="string">&quot;console.log(&#x27;script load onerror&#x27;)&quot;</span>&gt;&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// script load onerror</span></span><br></pre></td></tr></table></figure>

<p>如果要全局捕获静态资源加载的错误，需要给 addEventListener 方法增加第三个参数，即设置useCapture 为 ture：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">window</span>.addEventListener(<span class="string">&#x27;error&#x27;</span>, <span class="function"><span class="keyword">function</span>(<span class="params">event</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;window.addEventListener catch error:&#x27;</span>, event.message)</span><br><span class="line">&#125;, <span class="literal">true</span>); </span><br></pre></td></tr></table></figure>

<p>加载一个错误的JavaSctipt文件:</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">&lt;script src=<span class="string">&quot;https://misc.360buyimg.com/jdf/lib/jquery-1.6.4.000.js&quot;</span>&gt;&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// window.addEventListener catch error: &lt;script src=​&quot;https:​/​/​misc.360buyimg.com/​jdf/​lib/​jquery-1.6.4.000.js&quot;&gt;​&lt;/script&gt;​</span></span><br></pre></td></tr></table></figure>

<ol start="3">
<li>异步错误</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">setTimeout</span>(<span class="function">() =&gt;</span> &#123;</span><br><span class="line">  <span class="built_in">console</span>.log(a)</span><br><span class="line">&#125;, <span class="number">1000</span>);</span><br><span class="line"></span><br><span class="line"><span class="comment">// window.onerror catch error: Uncaught ReferenceError: a is not defined</span></span><br><span class="line"><span class="comment">// window.addEventListener catch error: Uncaught ReferenceError: a is not defined</span></span><br></pre></td></tr></table></figure>

<p>从上面的例子可以看出，GlobalEventHandlers.onerror 适用于需要捕获全局的异常的情况。另外，同 try-catch 相比，window.onerror 和 window.addEventListener 可以捕获语法错误和异步错误，element.onerror 和 window.addEventListener 可以捕获静态资源加载失败的错误。</p>
<p>尽管 window.onerror 和 window.addEventListener 可以处理异步错误，但是对于 Promise 的异步错误，是捕获不到的。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(a)</span><br><span class="line">&#125;)</span><br><span class="line"></span><br><span class="line"><span class="comment">// Uncaught (in promise) ReferenceError: a is not defined</span></span><br></pre></td></tr></table></figure>

<h3 id="promise-catch"><a href="#promise-catch" class="headerlink" title="promise-catch"></a>promise-catch</h3><p>Promise 的错误需要使用 promise-catch 来捕获，这些错误可以是代码运行时的错误，也可以是我们处理业务逻辑时 reject 的错误。</p>
<ol>
<li>代码错误</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(a)</span><br><span class="line">&#125;).catch(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;promise catch error:&#x27;</span>, err.message)</span><br><span class="line">&#125;)</span><br><span class="line"></span><br><span class="line"><span class="comment">// promise catch error: a is not defined</span></span><br></pre></td></tr></table></figure>

<ol start="2">
<li>reject的错误</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> &#123;</span><br><span class="line">    reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">&#x27;error rejected!&#x27;</span>))</span><br><span class="line">&#125;).catch(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">&#x27;promise catch error:&#x27;</span>, err.message)</span><br><span class="line">&#125;)</span><br><span class="line"></span><br><span class="line"><span class="comment">// promise catch error: error rejected!</span></span><br></pre></td></tr></table></figure>

<p>promise-catch 的适用范围很明确，就是处理 Promise 的异常。但是这里有例外，async/await 虽然本质上还是 Promise 语法，但是可以被 try-catch 捕获。（因此我们提倡使用 async/await 来代替纯 Promise，这样子可以更方便的被捕获，如果你还是使用 Promise，要记得添加 catch事件，或者依赖全局捕获错误的方法。）</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">fn</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> &#123;</span><br><span class="line">        <span class="built_in">console</span>.log(a);</span><br><span class="line">        resolve();</span><br><span class="line">    &#125;)</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">async</span> <span class="function"><span class="keyword">function</span> <span class="title">test</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        <span class="keyword">await</span> fn();</span><br><span class="line">    &#125; <span class="keyword">catch</span> (err) &#123;</span><br><span class="line">        <span class="built_in">console</span>.log(<span class="string">&#x27;try-catch error:&#x27;</span>, err.message);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">test();</span><br><span class="line"></span><br><span class="line"><span class="comment">// try-catch error: a is not defined</span></span><br></pre></td></tr></table></figure>

<h3 id="unhandledrejection"><a href="#unhandledrejection" class="headerlink" title="unhandledrejection"></a>unhandledrejection</h3><p>我们开发的时候，如果有些 Promise 异常没有被处理，可以使用全局的方法来捕获，这里用到了 unhandledrejection 事件。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">window</span>.onunhandledrejection = <span class="function"><span class="keyword">function</span>(<span class="params">err</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;window.onunhandledrejection catch error:&#x27;</span>, err.reason);</span><br><span class="line">&#125;</span><br><span class="line"><span class="built_in">window</span>.addEventListener(<span class="string">&#x27;unhandledrejection&#x27;</span>, <span class="function"><span class="keyword">function</span>(<span class="params">event</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;window.addEventListener unhandledrejection catch error:&#x27;</span>, event.reason);</span><br><span class="line">&#125;);</span><br><span class="line"></span><br><span class="line"><span class="comment">// window.onunhandledrejection catch error: ReferenceError: a is not defined</span></span><br><span class="line"><span class="comment">// window.addEventListener unhandledrejection catch error: ReferenceError: a is not defined</span></span><br></pre></td></tr></table></figure>

<p>我们在写前端项目的时候一般都是使用框架的，除了上面的通用的捕获异常的方法，框架本身还提供了一些方法供我们使用。</p>
<h2 id="Vue-中捕获异常"><a href="#Vue-中捕获异常" class="headerlink" title="Vue 中捕获异常"></a>Vue 中捕获异常</h2><p>Vue 的官方文档没有专门的章节来介绍异常的处理。总的来说，在生产环境有以下几种方式（开发环境的错误通过控制台就可以看到，这里不再铺开，详见 Vue 官网中的 warnHandler 及 renderError）：</p>
<ul>
<li>errorHandler</li>
<li>errorCaptured</li>
</ul>
<h3 id="errorHandler"><a href="#errorHandler" class="headerlink" title="errorHandler"></a>errorHandler</h3><p>errorHandler 在 Vue 中用于捕获全局的错误：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">Vue.config.errorHandler = <span class="function"><span class="keyword">function</span> (<span class="params">err, vm, info</span>) </span>&#123;</span><br><span class="line">  <span class="built_in">console</span>.log(<span class="string">&#x27;vue errorHandler: &#x27;</span> + err);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>errorHandler 可以捕获的异常包含以下方面：</p>
<ol>
<li>组件的渲染和观察期间未捕获的错误</li>
</ol>
<p>需要注意的是 template 中如果引用一个不存在的变量的话是不会被 errorHandler 捕获的，这个错误需要使用 errorHandler 捕获。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br></pre></td><td class="code"><pre><span class="line">  &lt;template&gt;</span><br><span class="line">      &lt;div&gt;&#123;&#123;currentTime&#125;&#125;&lt;/div&gt;</span><br><span class="line">  &lt;/template&gt;</span><br><span class="line"></span><br><span class="line">  &lt;script&gt;</span><br><span class="line">  <span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">      name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">      data () &#123;</span><br><span class="line">          <span class="keyword">return</span> &#123;&#125;</span><br><span class="line">      &#125;</span><br><span class="line">  &#125;</span><br><span class="line">  &lt;/script&gt;</span><br><span class="line"></span><br><span class="line">  <span class="comment">// 没有捕获到异常</span></span><br><span class="line"><span class="string">``</span><span class="string">` </span></span><br><span class="line"><span class="string">稍微修改一下，在 data 中加入 currentTime 变量，但是赋值错误：</span></span><br><span class="line"><span class="string"></span></span><br><span class="line"><span class="string">`</span><span class="string">``</span> js</span><br><span class="line">  &lt;template&gt;</span><br><span class="line">      &lt;div&gt;&#123;&#123;currentTime&#125;&#125;&lt;/div&gt;</span><br><span class="line">  &lt;/template&gt;</span><br><span class="line"></span><br><span class="line">  &lt;script&gt;</span><br><span class="line">  <span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">      name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">      data () &#123;</span><br><span class="line">          <span class="keyword">return</span> &#123;</span><br><span class="line">              currentTime</span><br><span class="line">          &#125;</span><br><span class="line">      &#125;</span><br><span class="line">  &#125;</span><br><span class="line">  &lt;/script&gt;</span><br><span class="line"></span><br><span class="line">  <span class="comment">// vue errorHandler: ReferenceError: currentTime is not defined</span></span><br></pre></td></tr></table></figure>

<ol start="2">
<li>捕获组件生命周期钩子里的错误（版本&gt;=2.2.0）</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">&lt;template&gt;</span><br><span class="line">    &lt;div&gt;&#123;&#123;currentTime&#125;&#125;&lt;/div&gt;</span><br><span class="line">&lt;/template&gt;</span><br><span class="line"></span><br><span class="line">&lt;script&gt;</span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">    name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">    data () &#123;</span><br><span class="line">        <span class="keyword">return</span> &#123;</span><br><span class="line">            currentTime: <span class="built_in">Date</span>.now()</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;,</span><br><span class="line">    mounted () &#123;</span><br><span class="line">        <span class="built_in">console</span>.log(currentTime)</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// vue errorHandler: ReferenceError: currentTime is not defined</span></span><br></pre></td></tr></table></figure>

<ol start="3">
<li>自定义事件处理函数内部的错误（版本&gt;=2.4.0）</li>
</ol>
<p>我们假设子组件使用 $emit 方法触发了 change 事件：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">&lt;template&gt;</span><br><span class="line">    &lt;child @change=<span class="string">&quot;changeHandler&quot;</span> /&gt;</span><br><span class="line">&lt;/template&gt;</span><br><span class="line"></span><br><span class="line">&lt;script&gt;</span><br><span class="line"><span class="keyword">import</span> Child <span class="keyword">from</span> <span class="string">&#x27;./child&#x27;</span></span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">    name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">    components: &#123;</span><br><span class="line">        Child</span><br><span class="line">    &#125;,</span><br><span class="line">    methods: &#123;</span><br><span class="line">        changeHandler () &#123;</span><br><span class="line">            <span class="built_in">console</span>.log(changedValue)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// vue errorHandler: ReferenceError: changedValue is not defined</span></span><br></pre></td></tr></table></figure>

<ol start="4">
<li>v-on DOM 监听器内部抛出的错误（版本&gt;=2.6.0）</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">&lt;template&gt;</span><br><span class="line">    &lt;button v-on:click=<span class="string">&quot;clickHandler&quot;</span>&gt;click here&lt;/button&gt;</span><br><span class="line">&lt;/template&gt;</span><br><span class="line"></span><br><span class="line">&lt;script&gt;</span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">    name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">    methods: &#123;</span><br><span class="line">        clickHandler () &#123;</span><br><span class="line">            <span class="built_in">console</span>.log(target)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// vue errorHandler: ReferenceError: target is not defined</span></span><br></pre></td></tr></table></figure>

<ol start="5">
<li>如果任何被覆盖的钩子或处理函数返回一个 Promise 链 (例如 async 函数)，则来自其 Promise 链的错误也会被处理。(版本&gt;=2.6.0)</li>
</ol>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">&lt;template&gt;</span><br><span class="line">    &lt;button v-on:click=<span class="string">&quot;clickHandler&quot;</span>&gt;click here&lt;/button&gt;</span><br><span class="line">&lt;/template&gt;</span><br><span class="line"></span><br><span class="line">&lt;script&gt;</span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">    name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">    methods: &#123;</span><br><span class="line">        clickHandler () &#123;</span><br><span class="line">            <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">() =&gt;</span> &#123;</span><br><span class="line">                <span class="built_in">console</span>.log(target)</span><br><span class="line">            &#125;) <span class="comment">// 必须要return，否则不会被捕获</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// vue errorHandler: ReferenceError: target is not defined</span></span><br></pre></td></tr></table></figure>

<h3 id="errorCaptured"><a href="#errorCaptured" class="headerlink" title="errorCaptured"></a>errorCaptured</h3><p>errorCaptured 是 Vue 在 2.5.0 新增加的钩子函数，用于捕获来自子组件的错误。现在，我们依然假设子组件抛出了一个错误（这里依然保留上一节提到的 errorHandler 方法）：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line">&lt;template&gt;</span><br><span class="line">    &lt;child /&gt;</span><br><span class="line">&lt;/template&gt;</span><br><span class="line"></span><br><span class="line">&lt;script&gt;</span><br><span class="line"><span class="keyword">import</span> Child <span class="keyword">from</span> <span class="string">&#x27;./child&#x27;</span></span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> &#123;</span><br><span class="line">    name: <span class="string">&#x27;ErrorTest&#x27;</span>,</span><br><span class="line">    <span class="function"><span class="title">data</span>(<span class="params"></span>)</span> &#123;</span><br><span class="line">        <span class="keyword">return</span> &#123;</span><br><span class="line">            currentTime: <span class="built_in">Date</span>.now()</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;,</span><br><span class="line">    components: &#123;</span><br><span class="line">        Child</span><br><span class="line">    &#125;,</span><br><span class="line">    errorCaptured (err, vm, info) &#123;</span><br><span class="line">        <span class="built_in">console</span>.log(<span class="string">&#x27;vue errorCaptured: &#x27;</span> + err);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// vue errorCaptured: ReferenceError: current is not defined</span></span><br><span class="line"><span class="comment">// vue errorHandler: ReferenceError: current is not defined</span></span><br></pre></td></tr></table></figure>

<p>上面的例子显示，errorCaptured 先于 errorHandler 捕获了错误，如果不想再次被上级捕获，可以在钩子函数中返回 false 。附上Vue官网给出的<a target="_blank" rel="noopener" href="https://cn.vuejs.org/v2/api/#errorCaptured">错误传播规则</a>：</p>
<ul>
<li>默认情况下，如果全局的 config.errorHandler 被定义，所有的错误仍会发送它，因此这些错误仍然会向单一的分析服务的地方进行汇报。</li>
<li>如果一个组件的继承或父级从属链路中存在多个 errorCaptured 钩子，则它们将会被相同的错误逐个唤起。</li>
<li>如果此 errorCaptured 钩子自身抛出了一个错误，则这个新错误和原本被捕获的错误都会发送给全局的 config.errorHandler。</li>
<li>一个 errorCaptured 钩子能够返回 false 以阻止错误继续向上传播。本质上是说“这个错误已经被搞定了且应该被忽略”。它会阻止其它任何会被这个错误唤起的 errorCaptured 钩子和全局的 config.errorHandler。</li>
</ul>
<h2 id="React-中捕获异常"><a href="#React-中捕获异常" class="headerlink" title="React 中捕获异常"></a>React 中捕获异常</h2><p>React官网中有专门的章节介绍异常的章节——<a target="_blank" rel="noopener" href="https://react.docschina.org/docs/error-boundaries.html">错误边界</a>。</p>
<h3 id="错误边界"><a href="#错误边界" class="headerlink" title="错误边界"></a>错误边界</h3><p>错误边界的概念是 React 在 React 16 引入的概念，是为了解决部分 UI 的 JavaScript 错误引起的应用崩溃问题。</p>
<blockquote>
<p>错误边界是一种 React 组件，这种组件可以捕获并打印发生在其子组件树任何位置的 JavaScript 错误，并且，它会渲染出备用 UI，而不是渲染那些崩溃了的子组件树。错误边界在渲染期间、生命周期方法和整个组件树的构造函数中捕获错误。<br>如果一个 class 组件中定义了 static getDerivedStateFromError() 或 componentDidCatch() 这两个生命周期方法中的任意一个（或两个）时，那么它就变成一个错误边界。<br>只有 class 组件才可以成为错误边界组件。</p>
</blockquote>
<p>基于上面的说明，我们的错误边界的组件可以这样写：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> React <span class="keyword">from</span> <span class="string">&#x27;react&#x27;</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">import</span> Default <span class="keyword">from</span> <span class="string">&#x27;/default&#x27;</span></span><br><span class="line"><span class="keyword">import</span> &#123; uploadError &#125; <span class="keyword">from</span> <span class="string">&#x27;../utils/error&#x27;</span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ErrorBoundary</span> <span class="keyword">extends</span> <span class="title">React</span>.<span class="title">Component</span> </span>&#123;</span><br><span class="line">  <span class="title">constructor</span> (<span class="params">props</span>) &#123;</span><br><span class="line">    <span class="built_in">super</span>(props)</span><br><span class="line">    <span class="built_in">this</span>.state = &#123; <span class="attr">hasError</span>: <span class="literal">false</span> &#125;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="keyword">static</span> getDerivedStateFromError (err) &#123;</span><br><span class="line">    <span class="comment">// 发生错误，显示降级后的UI</span></span><br><span class="line">    <span class="keyword">return</span> &#123; <span class="attr">hasError</span>: <span class="literal">true</span> &#125;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  componentDidCatch (err, info) &#123;</span><br><span class="line">    <span class="comment">// 可以将错误日志上报给服务器</span></span><br><span class="line">    uploadError(err)</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  render () &#123;</span><br><span class="line">    <span class="keyword">if</span> (<span class="built_in">this</span>.state.hasError) &#123;</span><br><span class="line">      <span class="keyword">return</span> <span class="xml"><span class="tag">&lt;<span class="name">Default</span> /&gt;</span></span></span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> <span class="built_in">this</span>.props.children</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">export</span> <span class="keyword">default</span> ErrorBoundary</span><br><span class="line"></span><br><span class="line"><span class="comment">// 使用：</span></span><br><span class="line">&lt;ErrorBoundary&gt;</span><br><span class="line">  &lt;Child /&gt;</span><br><span class="line">&lt;/ErrorBoundary&gt;</span><br></pre></td></tr></table></figure>

<p>错误边界的工作方式类似于 JavaScript 的 catch {}，不同的地方在于错误边界只针对 React 组件。错误边界无法捕获的错误有下面几个方面，这些异常需要使用 try-catch 等捕获：</p>
<ul>
<li>事件处理</li>
<li>异步代码</li>
<li>服务端渲染</li>
<li>它自身抛出来的错误（并非它的子组件）</li>
</ul>
<h2 id="iframe-异常"><a href="#iframe-异常" class="headerlink" title="iframe 异常"></a>iframe 异常</h2><p>当我们的页面引用了 iframe 的时候，也可以使用 onerror 方法捕获 iframe 的异常，但这种形式仅限于你自己的页面和 iframe 的页面同域名的情况：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">&lt;iframe src=<span class="string">&quot;./iframe.html&quot;</span>&gt;&lt;/iframe&gt;</span><br><span class="line">&lt;script&gt;</span><br><span class="line">    <span class="built_in">window</span>.frames[<span class="number">0</span>].onerror = <span class="function"><span class="keyword">function</span> (<span class="params">message</span>) </span>&#123;</span><br><span class="line">        <span class="built_in">console</span>.log(<span class="string">&#x27;iframe error: &#x27;</span> + message);</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&lt;/script&gt;</span><br><span class="line"></span><br><span class="line"><span class="comment">// iframe error: Uncaught ReferenceError: a is not defined</span></span><br></pre></td></tr></table></figure>

<h2 id="页面崩溃"><a href="#页面崩溃" class="headerlink" title="页面崩溃"></a>页面崩溃</h2><p>页面崩溃和上面提到的异常捕获的情况是不一样的，页面崩溃时，JavaScript 代码已经不执行了。但还是有办法来监控到页面崩溃的，目前有两种：一个是load 和 beforeunload 结合， 另外一个是基于 Service Worker。</p>
<h3 id="load-和-beforeunload-事件"><a href="#load-和-beforeunload-事件" class="headerlink" title="load 和 beforeunload 事件"></a>load 和 beforeunload 事件</h3><p>我们先来看下代码：</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">window</span>.addEventListener(<span class="string">&#x27;load&#x27;</span>, <span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">  sessionStorage.setItem(<span class="string">&#x27;good_exit&#x27;</span>, <span class="string">&#x27;pending&#x27;</span>);</span><br><span class="line">  <span class="built_in">setInterval</span>(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">    sessionStorage.setItem(<span class="string">&#x27;time_before_crash&#x27;</span>, <span class="keyword">new</span> <span class="built_in">Date</span>().toString());</span><br><span class="line">  &#125;, <span class="number">1000</span>);</span><br><span class="line">&#125;);</span><br><span class="line"></span><br><span class="line"><span class="built_in">window</span>.addEventListener(<span class="string">&#x27;beforeunload&#x27;</span>, <span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">  sessionStorage.setItem(<span class="string">&#x27;good_exit&#x27;</span>, <span class="string">&#x27;true&#x27;</span>);</span><br><span class="line">&#125;);</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span>(sessionStorage.getItem(<span class="string">&#x27;good_exit&#x27;</span>) &amp;&amp;</span><br><span class="line">  sessionStorage.getItem(<span class="string">&#x27;good_exit&#x27;</span>) !== <span class="string">&#x27;true&#x27;</span>) &#123;</span><br><span class="line">  <span class="comment">/*</span></span><br><span class="line"><span class="comment">      insert crash logging code here</span></span><br><span class="line"><span class="comment">  */</span></span><br><span class="line">  alert(<span class="string">&#x27;Hey, welcome back from your crash, looks like you crashed on: &#x27;</span> + sessionStorage.getItem(<span class="string">&#x27;time_before_crash&#x27;</span>));</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>从上面的代码来看，这个方法其实是利用了页面崩溃时无法触发 beforeunload 事件来实现的。页面加载完成后，在 sessionStorage 中存储 good_exit 的值为 pending。如果页面正常关闭， 会触发 beforeunload 事件，在 beforeunload 事件中，我们将 good_exit 的值重置为 true。如果页面崩溃了，刷新页面时，从 sessionStorage 中读取到的值就是 pending 而不是 true。</p>
<p>用上面的方式处理有以下问题：</p>
<ol>
<li><p>由于是 sessionStorage 存储的值，页面崩溃后如果用户关闭页面或重新打开浏览器，sessionStorage 中存储的 good_exit 值我们是获取不到的；</p>
</li>
<li><p>如果前进或后退，页面会从缓存中加载，有时候是不会触发 load 事件的。</p>
<p>即使存在上面的问题，但这个方法对我们依然有借鉴意义。页面崩溃时，JavaScript 不会执了，DOM 也卸载了，我们对页面的渲染是无能为力的。但我们可以在用户再次刷新页面时捕获到上次的崩溃信息，并将崩溃上报到监控系统。如果监控系统收到大量的崩溃信息，就说明我们的页面出现了严重的问题了，这时候我们就需要想办法复现或者从代码逻辑层面找到崩溃原因了。</p>
</li>
</ol>
<h3 id="基于-Service-Worker"><a href="#基于-Service-Worker" class="headerlink" title="基于 Service Worker"></a>基于 Service Worker</h3><p>基于 Service Worker 的方案其实也是利用了页面崩溃时无法触发 beforeunload 事件来实现的，与 load 和 beforeunload 的区别是 Service Worker 相对于驱动应用的主 JavaScript 线程，它运行在其他线程中，即使网页崩溃了，Service Worker 一般情况下也不会崩溃。所以，我们不需要等到用户再次刷新页面才能获取上次的崩溃信息了。</p>
<figure class="highlight js"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 页面 JavaScript 代码</span></span><br><span class="line"><span class="keyword">if</span> (navigator.serviceWorker.controller !== <span class="literal">null</span>) &#123;</span><br><span class="line">  <span class="keyword">let</span> HEARTBEAT_INTERVAL = <span class="number">5</span> * <span class="number">1000</span>; <span class="comment">// 每五秒发一次心跳</span></span><br><span class="line">  <span class="keyword">let</span> sessionId = uuid();</span><br><span class="line">  <span class="keyword">let</span> heartbeat = <span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">    navigator.serviceWorker.controller.postMessage(&#123;</span><br><span class="line">      type: <span class="string">&#x27;heartbeat&#x27;</span>,</span><br><span class="line">      id: sessionId,</span><br><span class="line">      data: &#123;&#125; <span class="comment">// 附加信息，如果页面 crash，上报的附加数据，比如页面地址等</span></span><br><span class="line">    &#125;);</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="built_in">window</span>.addEventListener(<span class="string">&quot;beforeunload&quot;</span>, <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">    navigator.serviceWorker.controller.postMessage(&#123;</span><br><span class="line">      type: <span class="string">&#x27;unload&#x27;</span>,</span><br><span class="line">      id: sessionId</span><br><span class="line">    &#125;);</span><br><span class="line">  &#125;);</span><br><span class="line">  <span class="built_in">setInterval</span>(heartbeat, HEARTBEAT_INTERVAL);</span><br><span class="line">  heartbeat();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// Service Worker</span></span><br><span class="line"><span class="keyword">const</span> CHECK_CRASH_INTERVAL = <span class="number">10</span> * <span class="number">1000</span>; <span class="comment">// 每 10s 检查一次</span></span><br><span class="line"><span class="keyword">const</span> CRASH_THRESHOLD = <span class="number">15</span> * <span class="number">1000</span>; <span class="comment">// 15s 超过15s没有心跳则认为已经 crash</span></span><br><span class="line"><span class="keyword">const</span> pages = &#123;&#125;</span><br><span class="line"><span class="keyword">let</span> timer</span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">checkCrash</span>(<span class="params"></span>) </span>&#123;</span><br><span class="line">  <span class="keyword">const</span> now = <span class="built_in">Date</span>.now()</span><br><span class="line">  <span class="keyword">for</span> (<span class="keyword">var</span> id <span class="keyword">in</span> pages) &#123;</span><br><span class="line">    <span class="keyword">let</span> page = pages[id]</span><br><span class="line">    <span class="keyword">if</span> ((now - page.t) &gt; CRASH_THRESHOLD) &#123;</span><br><span class="line">      <span class="comment">// 上报 crash</span></span><br><span class="line">      <span class="keyword">delete</span> pages[id]</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">if</span> (<span class="built_in">Object</span>.keys(pages).length == <span class="number">0</span>) &#123;</span><br><span class="line">    <span class="built_in">clearInterval</span>(timer)</span><br><span class="line">    timer = <span class="literal">null</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">worker.addEventListener(<span class="string">&#x27;message&#x27;</span>, <span class="function">(<span class="params">e</span>) =&gt;</span> &#123;</span><br><span class="line">  <span class="keyword">const</span> data = e.data;</span><br><span class="line">  <span class="keyword">if</span> (data.type === <span class="string">&#x27;heartbeat&#x27;</span>) &#123;</span><br><span class="line">    pages[data.id] = &#123;</span><br><span class="line">      t: <span class="built_in">Date</span>.now()</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">if</span> (!timer) &#123;</span><br><span class="line">      timer = <span class="built_in">setInterval</span>(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">        checkCrash()</span><br><span class="line">      &#125;, CHECK_CRASH_INTERVAL)</span><br><span class="line">    &#125;</span><br><span class="line">  &#125; <span class="keyword">else</span> <span class="keyword">if</span> (data.type === <span class="string">&#x27;unload&#x27;</span>) &#123;</span><br><span class="line">    <span class="keyword">delete</span> pages[data.id]</span><br><span class="line">  &#125;</span><br><span class="line">&#125;)</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p>上面代码的思路是：</p>
<ol>
<li>网页加载后，通过 postMessage API 每 5s 给 sw 发送一个心跳，表示自己的在线，sw 将在线的网页登记下来，更新登记时间；</li>
<li>网页在 beforeunload 时，通过 postMessage API 告知自己已经正常关闭，sw 将登记的网页清除；</li>
<li>如果网页在运行的过程中 crash 了，sw 中的 running 状态将不会被清除，更新时间停留在奔溃前的最后一次心跳；</li>
<li>Service Worker 每 10s 查看一遍登记中的网页，发现登记时间已经超出了一定时间（比如 15s）即可判定该网页 crash 了。</li>
</ol>
<p>同样的，Service Worker捕获的错误对前端监控是很有用的。</p>
<h1 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h1><p>具体到实际工作中，我们要处理的异常分为以下几种：</p>
<ol>
<li>语法错误及代码异常：对可疑区域增加 try-catch，全局增加 window.onerror;</li>
<li>数据请求异常：使用 promise-catch 处理 Promise 异常，使用 unhandledrejection 处理未捕获的Promise异常，使用 try-catch 处理 async/await 异常;</li>
<li>静态资源加载异常：在元素上添加 onerror，全局增加 window.addEventListener；</li>
<li>白屏：Vue 使用 errorHandler， React 使用 componentDidCatch，渲染备用UI；</li>
<li>iframe异常：同域条件下使用 onerror。</li>
<li>页面崩溃：load 和 beforeunload 结合或者使用 Service Worker。</li>
</ol>
</div><div class="post-copyright"><div class="post-copyright__author"><span class="post-copyright-meta">文章作者: </span><span class="post-copyright-info"><a href="mailto:undefined">YolkPie</a></span></div><div class="post-copyright__type"><span class="post-copyright-meta">文章链接: </span><span class="post-copyright-info"><a href="https://yolkpie.net/2021/01/28/%E5%89%8D%E7%AB%AF%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/">https://yolkpie.net/2021/01/28/%E5%89%8D%E7%AB%AF%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/</a></span></div><div class="post-copyright__notice"><span class="post-copyright-meta">版权声明: </span><span class="post-copyright-info">本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> 许可协议。转载请注明来自 <a href="https://yolkpie.net" target="_blank">YolkPie</a>！</span></div></div><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/%E5%BC%82%E5%B8%B8/">异常</a></div><div class="post_share"><div class="social-share" data-image="https://img11.360buyimg.com/imagetools/jfs/t1/177355/25/23849/1202313/627b84b8E2d78637c/dc9cbe48ca92c62f.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css"/><script src="https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js"></script></div></div><nav class="pagination-post" id="pagination"><div class="prev-post pull-left"><a href="/2021/02/03/SameSiteForCookie/"><img class="prev-cover" data-src="https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg" onerror="onerror=null;src='/img/404.jpg'"><div class="pagination-info"><div class="label">上一篇</div><div class="prev_info">SameSiteForCookie</div></div></a></div><div class="next-post pull-right"><a href="/2021/01/28/React%20Hooks%E7%9A%84%E5%B8%B8%E8%A7%81%E5%BA%94%E7%94%A8%E5%8F%8A%E4%B8%80%E4%BA%9B%E5%8E%9F%E7%90%86/"><img class="next-cover" data-src="https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg" onerror="onerror=null;src='/img/404.jpg'"><div class="pagination-info"><div class="label">下一篇</div><div class="next_info">React Hooks的常见应用及一些原理</div></div></a></div></nav><div class="relatedPosts"><div class="relatedPosts_headline"><i class="fas fa-thumbs-up fa-fw"></i><span> 相关推荐</span></div><div class="relatedPosts_list"><div class="relatedPosts_item"><a href="/2021/12/23/前端生产环境debugger技巧/" title="生产环境debugger"><img class="relatedPosts_cover" data-src="https://img12.360buyimg.com/imagetools/jfs/t1/169203/7/4620/173190/601266a8E8ad356b4/4fdec47d3f9e5259.png"><div class="relatedPosts_main is-center"><div class="relatedPosts_date"><i class="far fa-calendar-alt fa-fw"></i> 2021-12-23</div><div class="relatedPosts_title">生产环境debugger</div></div></a></div><div class="relatedPosts_item"><a href="/2021/03/23/从sgm-web指标来看页面加载速度优化/" title="从sgm-web指标来看页面加载速度优化"><img class="relatedPosts_cover" data-src="https://img14.360buyimg.com/imagetools/jfs/t1/158535/22/7215/96620/602f2a91Eb6020785/997b23c6f02a6baa.jpg"><div class="relatedPosts_main is-center"><div class="relatedPosts_date"><i class="far fa-calendar-alt fa-fw"></i> 2021-03-23</div><div class="relatedPosts_title">从sgm-web指标来看页面加载速度优化</div></div></a></div></div></div></article></main><footer id="footer" data-type="color"><div id="footer-wrap"><div class="copyright">&copy;2020 - 2022 By YolkPie</div><div class="framework-info"><span>驱动 </span><a target="_blank" rel="noopener" href="https://hexo.io"><span>Hexo</span></a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly"><span>Butterfly</span></a></div></div></footer></div><section class="rightside" id="rightside"><div id="rightside-config-hide"><button id="readmode" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="font_plus" title="放大字体"><i class="fas fa-plus"></i></button><button id="font_minus" title="缩小字体"><i class="fas fa-minus"></i></button><button class="translate_chn_to_cht" id="translateLink" title="简繁转换">繁</button><button id="darkmode" title="浅色和深色模式转换"><i class="fas fa-adjust"></i></button></div><div id="rightside-config-show"><button id="rightside_config" title="设置"><i class="fas fa-cog"></i></button><button class="close" id="mobile-toc-button" title="目录"><i class="fas fa-list-ul"></i></button><button id="go-up" title="回到顶部"><i class="fas fa-arrow-up"></i></button></div></section><script src="https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js"></script><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="/js/tw_cn.js"></script><script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js"></script><script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><script src="https://cdn.jsdelivr.net/npm/instant.page/instantpage.min.js" type="module" defer></script><script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js" async></script></body></html>